services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - auth
      - converter
      - db
  auth:
    build: ./auth
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/lab_db
    depends_on:
      - db

  converter:
    build: ./converter
    ports:
      - "8002:8002"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lab_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: